#!/usr/bin/python3 
# SPDX-License-Identifier: MIT

import fcntl
import os
import struct
import sys
import threading
import struct


HEADER = struct.Struct("<H")

def open_tap(name, device="/dev/net/tun"):
    TUNSETIFF = 0x400454CA
    IFF_NO_PI = 0x1000
    O_RDWR = 0x2
    IFF_TAP = 0x0002

    flags = IFF_TAP | IFF_NO_PI
    name = name.encode()
    ifr_name = name + b"\x00" * (16 - len(name))
    ifr = struct.pack("16sH22s", ifr_name, flags, b"\x00" * 22)

    fd = os.open(device, O_RDWR)
    fcntl.ioctl(fd, TUNSETIFF, ifr)
    return fd


def open_macvtap(name):
    with open(f"/sys/class/net/{name}/ifindex") as f:
        idx = f.read().strip()
    return open_tap(name=name, device="/dev/tap" + idx)


vtap = open_macvtap(sys.argv[1])


def t1():
    while True:
        (length, ) = HEADER.unpack(sys.stdin.buffer.read(HEADER.size))
        buf = sys.stdin.buffer.read(length)
        os.write(vtap, buf)


threading.Thread(target=t1, daemon=True).start()

while True:
    buf = os.read(vtap, 1522)
    sys.stdout.buffer.write(HEADER.pack(len(buf)))
    sys.stdout.buffer.write(buf)
    sys.stdout.buffer.flush()
