targets:
  main:
    resources:
      RawSerialPort:
        port: "/dev/ttyUSB0"
    drivers:
      ManualPowerDriver:
        name: "example"
      SerialDriver:
        txdelay: 0.01
      BareboxDriver:
        prompt: 'barebox@[^:]+:[^ ]+ '
        bootstring: 'Modules linked in'
      ShellDriver:
        prompt: 'root@\w+:[^ ]+ '
        login_prompt: ' login: '
        username: 'root'
      BareboxStrategy: {}
