#!/bin/bash

# Boot U-Boot to the command prompt on a particular target and bring up a
# console

usage() {
	if [ -n "$1" ]; then
		echo "Failed : $1"
	else
		echo "Connect to a running U-Boot ready, to enter commands"
	fi
	echo "Usage: ub-cli [-BcDhLsTv] [-a <opt> ] [-d <dir>] [-x <dir>] [-e <file> ] [-l <file>] <target>"
	echo " -a  <opt> Adjust build, e.g. -a NET_LWIP -a ~CMD_MEM"
	echo " -B  Don't build U-Boot"
	echo " -c  Run 'make mrproper' before building"
	echo " -d  <dir> Set build directory"
	echo " -D  Enable debugging"
	echo " -e  <file> Log Dediprog EM100-Pro trace to a file"
	echo " -h  Help"
	echo " -l  <file> Log console output to file"
	echo " -o  <file> Set labgrid log-output file"
	echo " -s  Send over USB (instead of writing to boot media)"
	echo " -T  Don't bootstrap U-Boot"
	echo " -v  Verbose mode"
	echo " -x  <dir> Set extra build directory"
	exit 1
}

mydir=$(dirname $0)

. ${mydir}/lg-env

allowed_args="a:Bcd:De:hl:o:sTvx:"
. ${mydir}/get_args.sh

ret=0
labgrid-client ${V} ${debug} ${vars} -r ${target} -s uboot -a ${log_output}
	console ${console_log} ${listen_only} ${log_output} || ret=$?

labgrid-client ${V} -r "${target}" release -a

[[ $ret -ne 0 ]] && exit $ret
